# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github',
            field=models.URLField(default='https://github.com/scottc11', max_length=250),
        ),
    ]
